on: [push]

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    name: A job to get the list of changed files
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get list of changed files
        uses: ./ # Uses an action in the root directory
        id: changed_files
      - name: Get the output time
        run: echo "${{ steps.changed_files.outputs.CHANGED_FILES }}"
