on: [push]

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    name: A job to get the list of changed files
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get list of changed files
        uses: ./ # Uses an action in the root directory
        id: changed_files
        with:
          target_branch: master
      - name: Get files changed
        run: echo "${{ steps.changed_files.outputs.CHANGED_FILES }}"
      - name: Get extensions of changed files
        run: echo "${{ steps.changed_files.outputs.CHANGED_FILES_EXTENSIONS }}"
      - name: Echo if changed js
        if: "contains(steps.changed_files.outputs.CHANGED_FILES_EXTENSIONS, 'js')"
        run: echo JS files changed
      - name: Echo if changed yml
        if: "contains(steps.changed_files.outputs.CHANGED_FILES_EXTENSIONS, 'yml')"
        run: echo YML files changed
